<<<<<<< HEAD
=======
# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
>>>>>>> ae5c2bdf6afdad7b21b21e98d09567340f1aca58
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
<<<<<<< HEAD
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
env:
  global:
    - ROS_PARALLEL_TEST_JOBS="-j1"
    - CATKIN_PARALLEL_TEST_JOBS="-j1"
  matrix:
    - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false  BEFORE_SCRIPT='$CI_SOURCE_PATH/.travis_before_script_jsk_recognition_utils.bash'
    - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
    - ROS_DISTRO=jade    ROSWS=wstool BUILDER=catkin   USE_DEB=true
    - ROS_DISTRO=kinetic ROSWS=wstool BUILDER=catkin   USE_DEB=true
script: source .travis/travis.sh
before_script:
  - export ROS_PARALLEL_JOBS="-j2 -l2"
=======
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
env:
  - ROS_DISTRO=hydro AFTER_INSTALL=""
  - ROS_DISTRO=hydro USE_CATKIN_MAKE=true BEFORE_SCRIPT="pwd; git clone http://github.com/jsk-ros-pkg/jsk_common_msgs" NOT_TEST_INSTALL=true
  - ROS_DISTRO=hydro AFTER_INSTALL="" TEST_PKGS=" "
  - ROS_DISTRO=hydro AFTER_INSTALL="" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
  - ROS_DISTRO=hydro AFTER_INSTALL="mongodb-clients"
  - ROS_DISTRO=hydro AFTER_INSTALL="ros-hydro-roseus"
  - ROS_DISTRO=hydro BEFORE_SCRIPT="pwd; git clone http://github.com/jsk-ros-pkg/jsk_common_msgs"
  - ROS_DISTRO=hydro USE_JENKINS="true" NO_SUDO="true"
  - ROS_DISTRO=indigo BUILDER='not-compile'
  - ROS_DISTRO=indigo BUILDER='not-compile' TRAVIS_REPO_SLUG=jsk-ros-pkg/jsk_travis
  - ROS_DISTRO=indigo BUILDER='not-compile' TRAVIS_REPO_SLUG=jsk-ros-pkg/jsk_travis TRAVIS_BRANCH=master TRAVIS_COMMIT='HEAD' TRAVIS_PULL_REQUEST='false'
  - ROS_DISTRO=jade BUILDER='not-compile'
  - ROS_DISTRO=jade BUILDER='not-compile' TRAVIS_REPO_SLUG=jsk-ros-pkg/jsk_travis
  - ROS_DISTRO=jade BUILDER='not-compile' TRAVIS_REPO_SLUG=jsk-ros-pkg/jsk_travis TRAVIS_BRANCH=master TRAVIS_COMMIT='HEAD' TRAVIS_PULL_REQUEST='false'
  - ROS_DISTRO=kinetic BUILDER='not-compile'
before_script:
  - mkdir .travis; cp * .travis # need to copy, since directory starting from . is ignoreed by catkin build
  - export BEFORE_SCRIPT="rm -fr jsk_travis/CATKIN_IGNORE; ${BEFORE_SCRIPT}"
  - if [ "${USE_CATKIN_MAKE}" == "true" ] ;then sed -i 's@catkin build -i -v --limit-status-rate 0.001@catkin_make@' .travis/travis.sh; fi
  - if [ "${USE_CATKIN_MAKE}" == "true" ] ;then sed -i 's@catkin run_tests --no-deps --limit-status-rate 0.001@catkin_make run_tests@' .travis/travis.sh; fi
  - if [ "${USE_CATKIN_MAKE}" == "true" ] ;then export CATKIN_PARALLEL_JOBS="--no-color" ; fi
script:
  - if [ "${ROS_DISTRO}" = "indigo" -o "${ROS_DISTRO}" = "jade" -o "${ROS_DISTRO}" = "kinetic" -o "${USE_JENKINS}" = "true" ] ; then sed -i 's@cat .travis/travis.sh@cat travis.sh@' .travis/travis_jenkins.py; fi
  - source .travis/travis.sh
  - if [ "${AFTER_INSTALL}" != "" ] ; then sudo apt-get install -f ${AFTER_INSTALL}; fi
>>>>>>> ae5c2bdf6afdad7b21b21e98d09567340f1aca58
